title: Belwerks
email: hello@belwerks.com
owner: Stephen Belyea
description: >-
  Stephen Belyea is an Accessibility Nerd + Front End Developer with over a 
  decade's experience building things for the web. He likes to write stuff too.

domain: belwerks.com
url: https://belwerks.com

link_linkedin: https://www.linkedin.com/in/sebelyea
link_github: https://github.com/stephenbelyea
link_codepen: https://codepen.io/belwerks
link_medium: https://medium.com/@belwerks
link_mastodon: https://a11y.info/@belwerks

theme: minima
plugins:
  - jekyll-feed

jekyll-figure:
  paragraphs: false
